# -*- coding: utf-8 -*-
"""Reddit_Nursing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWPjctKxLOSIugmP8A_z7xbczs5RbM-0
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np 
from google.colab import files

df = pd.read_excel('/content/drive/My Drive/Reddit Nursing/comments_nursing.xlsx', usecols=['id','link_id','parent_id'], header=0,nrows=50001,index_col=False)
df.head()

df.dtypes

gk = df.groupby('link_id')
keys = []
for i in gk.groups.keys():
  keys.append(i)

final_List={}
final_ans = {}

#count = 1
for j in keys:
  first_group = gk.get_group(j)  #Getting instances of the each group
  first_group = first_group.astype('|S')

  im_cmt = first_group.query('link_id==parent_id') #Getting immediate comments of each group

  m_list = [x for x in im_cmt['id']]

  table1 = first_group
  table1['parent_id']=table1['parent_id'].str.slice(3,)
  
  i = 0
  while i<len(m_list):
    sub_list = [m_list[i]]
    
    ans = []

    while sub_list:
      val = sub_list[0]

      new_id = table1.loc[table1['parent_id']==val]
      res = [x for x in new_id['id']]
      ans += res

      sub_list += res
      sub_list.pop(0)
    
    final_List[m_list[i]]=ans
    new_final_list = {}
    for k in final_List:
      if final_List[k]!=[]:
        new_final_list[k] = final_List[k]
        
    
    

    i += 1
  # final_ans[count] = new_final_list
  # count += 1

print(new_final_list)

df1 = (pd.DataFrame.from_dict(new_final_list, orient='index')
                  .stack()
                  .reset_index(level=1, drop=True)
                  .reset_index())
df1.columns = ['Parent_id','Comment_id']
df1['Parent_id']=df1['Parent_id'].str.decode('utf-8')
df1['Comment_id']=df1['Comment_id'].str.decode('utf-8')
print (df1)

df1.to_csv("Results.csv", index=False)

files.download('Results.csv')
